### ISSUE TITLE
训练那么久才出一个场景，不是说对新的图片可以生成相应的场景吗？

### ISSUE THREAD

**Issue by lishulincug** [skyhehe123/AutoRF-pytorch#4]
训练那么久才出一个场景，不能传入新的图片生成结果吗？

**Comment by skyhehe123** [comment]
@lishulincug 可以的啊， 这是conditional nerf， 有汽车的roi + bbox作为输入就可以重建了啊。

**Comment by lishulincug** [comment]
> 

那可以生成mesh和纹理吗，这里都是gif获取图片

**Comment by lishulincug** [comment]
> @lishulincug 可以的啊， 这是conditional nerf， 有汽车的roi + bbox作为输入就可以重建了啊。

具体代码是在哪里呀

**Comment by lishulincug** [comment]
方便回一下吗？

**Comment by HTR625** [comment]
> 训练那么久才出一个场景，不能传入新的图片生成结果吗？



您好，方便问下您传入新的图片生成结果这个问题您解决了吗？
